// Project Name: Wireless Network Simulaor
// File: Receiver.h
// File Description: This file contains the interface for the Receiver class. 
//                   The class reads the data generated by the GUI and parses
//                   it into the Grid class, for further computation.

#ifndef RECEIVER_H
#define RECEIVER_H

#include <iostream>
#include <string>
#include <vector>
#include <fstream>

class Receiver {
  public:
  Receiver();

  void read_data_from_GUI(const std::string & filename);
  void parse_data();
  void print_file_data();

  // Accessible to other classes
  int grid_size;
  int num_of_base_stations;
  int base_station_radius;
  int num_of_nodes;
  int node_radius;

  // These are then parsed into a Node and BaseStation class.
  std::vector<std::string> unparsed_bs_data;
  std::vector<std::string> unparsed_node_data;
  
  private:
  std::vector<std::string> file_data_;

};

#endif // RECEIVER_H
