// Project Name: Wireless Network Simulaor
// File: DataCollector.hpp
// File Description: This file contains the interface for the Receiver class. 
//                   The class reads the data generated by the GUI and parses
//                   it into the Grid class, for further computation.

#ifndef RECEIVER_H
#define RECEIVER_H

#include <string>


class Receiver {
  public:
  Receiver(const std::string & filename);

  void read_data_from_GUI();
  void parse_data();

};

#endif // RECEIVER_H
